# Generated by Django 5.0.6 on 2024-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_abstract_exhibitor_reviewer_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='role',
            field=models.CharField(blank=True, choices=[('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee'), ('exhibitor', 'Exhibitor'), ('admin', 'Admin'), ('event_organizer', 'Event Organizer'), ('reviewer', 'Reviewer')], default='attendee', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
