# Generated by Django 5.0.6 on 2024-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventuser_profile_eventuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'default_related_name': 'event_user', 'permissions': (('view_user', 'Can view user'), ('add_speaker', 'Can add speaker'), ('add_sponsor', 'Can add sponsor'), ('change_event', 'Can edit event'), ('delete_event', 'Can delete event'), ('change_user', 'Can edit user'), ('delete_user', 'Can delete user'), ('add_admin', 'Can add admin'), ('add_event_organiser', 'Can add event organiser'), ('add_exhibitor', 'Can add exhibitor'), ('add_venue', 'Can add venue'), ('change_venue', 'Can edit venue'), ('delete_venue', 'Can delete venue'), ('add_agenda', 'Can add agenda'), ('change_agenda', 'Can edit agenda'), ('delete_agenda', 'Can delete agenda'), ('add_session', 'Can add session'), ('change_session', 'Can edit session'), ('delete_session', 'Can delete session'), ('add_reviewer', 'Can add reviewer'), ('add_abstract', 'Can add abstract'), ('change_abstract', 'Can edit abstract'), ('delete_abstract', 'Can delete abstract'), ('view_review', 'Can view review'), ('review_abstract', 'Can review abstract'), ('add_review', 'Can add review'), ('change_review', 'Can edit review'), ('add_showcase', 'Can add showcase'), ('view_showcase', 'Can view showcase'), ('change_showcase', 'Can edit showcase'), ('delete_showcase', 'Can delete showcase'))},
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='username',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='role',
            field=models.CharField(choices=[('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee'), ('reviewer', 'Reviewer'), ('admin', 'Admin'), ('event_organiser', 'Event Organiser'), ('exhibitor', 'Exhibitor')], default='attendee', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
