# Generated by Django 5.0.6 on 2024-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_eventuser_options_remove_eventuser_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'default_related_name': 'event_user', 'permissions': (('view_user', 'Can view user'), ('add_speaker', 'Can add speaker'), ('add_sponsor', 'Can add sponsor'), ('change_event', 'Can edit event'), ('delete_event', 'Can delete event'), ('change_user', 'Can edit user'), ('delete_user', 'Can delete user'), ('add_admin', 'Can add admin'))},
        ),
        migrations.RenameField(
            model_name='eventuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='role',
            field=models.CharField(blank=True, choices=[('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee'), ('exhibitor', 'Exhibitor'), ('admin', 'Admin'), ('event_organizer', 'Event Organizer'), ('reviewer', 'Reviewer')], default='attendee', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='physicalevent',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact_phone',
            field=models.CharField(max_length=15),
        ),
    ]
