# Generated by Django 5.0.6 on 2024-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_eventuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalevent',
            name='organizer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
