# Generated by Django 5.0.3 on 2024-06-07 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_physicalevent_organizer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='fullname',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='role',
            field=models.CharField(blank=True, choices=[('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee'), ('exhibitor', 'Exhibitor'), ('admin', 'Admin'), ('event_organizer', 'Event Organizer'), ('reviewer', 'Reviewer')], max_length=20, null=True),
        ),
    ]
