# Generated by Django 5.0.3 on 2024-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_eventuser_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
