# Generated by Django 5.0.3 on 2024-06-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='event_venues',
        ),
    ]
