# Generated by Django 5.0.3 on 2024-06-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_venue_event_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalevent',
            name='event_venues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_venues_choice', to='api.venue'),
        ),
    ]
