# Generated by Django 5.0.3 on 2024-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_physicalevent_event_venues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='contents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='download_content',
            new_name='reference_urls',
        ),
        migrations.RemoveField(
            model_name='exhibitorbooth',
            name='booth_size',
        ),
        migrations.RemoveField(
            model_name='exhibitorbooth',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='exhibitorbooth',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
