# Generated by Django 5.0.6 on 2024-06-08 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_contents_content_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalevent',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='physicalevent',
            name='target_audience',
        ),
        migrations.AlterField(
            model_name='physicalevent',
            name='organizer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
