# Generated by Django 5.0.6 on 2024-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_physicalevent_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalevent',
            name='organizer_contact',
        ),
        migrations.RemoveField(
            model_name='physicalevent',
            name='event_venues',
        ),
        migrations.AlterField(
            model_name='physicalevent',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.speaker'),
        ),
        migrations.AlterField(
            model_name='physicalevent',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.sponsor'),
        ),
        migrations.AddField(
            model_name='physicalevent',
            name='event_venues',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_venues_choice', to='api.venue'),
        ),
    ]
