# Generated by Django 5.0.6 on 2024-06-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_physicalevent_organizer_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='uploaded_at',
            new_name='Recording_at',
        ),
        migrations.AddField(
            model_name='videos',
            name='event_content_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_content_recording', to='api.event'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
