# Generated by Django 5.0.4 on 2024-06-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_uploaded_at_videos_recording_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitorbooth',
            name='exhibitor',
        ),
    ]
