# Generated by Django 5.0.4 on 2024-06-10 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_exhibitorbooth_exhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
