# Generated by Django 5.0.4 on 2024-06-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_speaker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user',
        ),
    ]
